### ISSUE TITLE
Links and buttons

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity.org#1]
## Description

We are using different types of links and buttons in the website design. Buttons are treated like links in Gutenberg, and they share some properties with common links, so it makes sense to process them together.

### 1. Common links
These are the common links used along the web, they aren't buttons. They are usually used inline text. Here you can see an example:

![Frontity_Framework_Landing_Play_Mode_-_InVision](https://user-images.githubusercontent.com/34552881/76077625-5a71c400-5fa1-11ea-8506-cd3ffd4084f3.png)

#### HTML
```
<a rel="noreferrer noopener" aria-label="Learn more (opens in a new tab)" href="https://frontity.org" target="_blank">Learn more</a>
```

#### Design / Logic
Normal status: 
* Default color `frontity`. //Get it from `state.theme.colors`

Hover status:
* Nothing special, just change the pointer.

Active status:
* Nothing special

### 2. Regular buttons
Most of the buttons will be the same, they may change its colors, but that should be processed by other processors. Here we have an example:

![Frontity_Framework_Landing_Play_Mode_-_InVision-2](https://user-images.githubusercontent.com/34552881/76077750-9d339c00-5fa1-11ea-914f-800c23fd793f.png)

Add the `default-button` CSS class

#### HTML
Gutenberg returns this HTML with the button component, always with the same classes:
```
<div class="wp-block-button default-button">
	<a class="wp-block-button__link">Get Started</a>
</div>
```
#### Design / Logic
>The `css` added is not valid, it's just to have a clearer picture of the logic

Hover status

Although the colors and css may be different, the `hover` effect should be something similar to this:
https://www.loom.com/share/6635463172824187ab69257583ec11ab

We can find this at [frontity.org](https://frontity.org) (the smooth transition is not implemented there).
```
move logo 2px right
add a layer with background rgba(255, 255, 255, 0.12)
add a transition to make it smooth -> transition: 0.25s ease
```
Unhover
```
Move logo to its position with smooth animation
Remove hover layer
```
Active status
```
Remove hover layer
Move whole button 2px down
```

### 3. Big Buttons
There are some buttons, that will behave as the common ones, but have a bigger size. We'll add a class `big-button`, and we can change the size. Here we have an example:

![Frontity_Framework_Landing_Play_Mode_-_InVision-3](https://user-images.githubusercontent.com/34552881/76079097-411e4700-5fa4-11ea-9972-8f5cf944a297.png)

#### HTML
```
<div class="wp-block-button big-button">
  <a class="wp-block-button__link">Big Button</a>
</div>
```
#### Design/Logic
We have to change:

### 4. Text Buttons
There will be some buttons, that don't have background and they look similar to just text. In order to differentiate them we can pass a class `text-button`. Here we have an example:

![Frontity_Framework_Landing_Play_Mode_-_InVision-4](https://user-images.githubusercontent.com/34552881/76079336-b8ec7180-5fa4-11ea-85a7-3de845a30a77.png)

#### HTML
```
<div class="wp-block-button text-button">
  <a class="wp-block-button__link">learn more</a>
</div>
```

#### Design / Logic

Hover status:
```
Fill the underline progressively from left to right
```
We can find a similar effect here:
https://www.loom.com/share/f98d1b9e93ba4259b16d383b96c77280

Not saying we have to implement it like this, but the example is from [this article](https://paulund.co.uk/css-animation-link-underline#left-to-right), in the section "left to right".

Unhover:
```
Unfill the underline progressively from left to right
```
Active:
```
Move it 2px down
```

**Comment by SantosGuillamot** [comment]
@michalczaplinski Following your recommendations. I've updated the issue in order to try to be more clear, let me know if you still have questions about it, remember that the Invision design could help as well.

Apart from that, I did a quick video trying to explain it:
https://www.loom.com/share/2b784cc19d8244b090c4cc61c50a3ba8

**Comment by michalczaplinski** [comment]
@SantosGuillamot Do we want the regular buttons, big buttons and "link" buttons to always include the frontity logo in them (as in the invision design) ? Or should the logo be optional?

**Comment by SantosGuillamot** [comment]
Right now, all the buttons and "link" buttons always have the frontity logo except in one case, where we use a different `svg`.
![Screenshot from 2020-03-07 13-25-52](https://user-images.githubusercontent.com/34552881/76143375-3a143900-6077-11ea-85d3-6c673ebecdba.png)

Currently, the HTML of the button with a different logo looks like this:
```
<div class="wp-block-button">
  <a class="wp-block-button__link has-text-color has-background css-h584oe">
    <img class="wp-image-4384 css-fwcrwd" src="https://wp.frontity.org/wp-content/uploads/2020/02/demo-icon.svg" alt="">Try Demo in your Browser
  </a>
</div>
```
Not sure if this is possible but maybe we should add some logic that if an `<img>` is included inside the button, use that for the logo and if not use the default (frontity logo).

We could also add a class to specify that we don't want logo at all, just in case it's needed in the future. But as all the current buttons have the Frontity logo, I would make this the default behavior and specify with a class in case we don't want it. 

What do you think?

**Comment by michalczaplinski** [comment]
Yeah, that sounds good. In that case I ll do the following:

DEFAULT: The button has a logo.

**'no-logo' class**: The button has no logo

**button has an img** We show the <img> instead of the default logo

> Currently, the HTML of the button with a different logo looks like this:
Do we have an example of this? Cannot see it in common-styles.

**Comment by SantosGuillamot** [comment]
I think that makes sense :slightly_smiling_face: 

I've split the buttons in `default`, `Button with different icon`,  `Button without logo` so it's clearer now.

**Comment by michalczaplinski** [comment]
@SantosGuillamot 

1. 
<img width="357" alt="Screenshot 2020-03-10 at 11 56 01" src="https://user-images.githubusercontent.com/5417266/76337995-1f83cf00-62c6-11ea-97ed-115817b32491.png">

I think this button also needs a separate CSS class, no? Because otherwise it's hard to distinguish it from the "regular" button just on the basis of the presence of the icon.

2. How are we going to pass the different background colors to those buttons?

3. Similarly don't we need to be able to specify the color of the icon inside the button?

**Comment by SantosGuillamot** [comment]
>I think this button also needs a separate CSS class, no? Because otherwise it's hard to distinguish it from the "regular" button just on the basis of the presence of the icon.

I thought that detecting an image inside the button was enough but if you feel it's better to add a class go ahead.

>* How are we going to pass the different background colors to those buttons?
>* Similarly don't we need to be able to specify the color of the icon inside the button?

This is handled by another [processor](https://github.com/frontity/frontity.org/issues/2), not only buttons but all the html elements.

**Comment by michalczaplinski** [comment]
@SantosGuillamot 

We're almost done here, but I just have a couple of small notes:

1. The color of the logo in this button is basically fixed, because it's added through wordpress. Is that a problem? 
<img width="306" alt="Screenshot 2020-03-11 at 09 53 33" src="https://user-images.githubusercontent.com/5417266/76430315-2e2dbd00-637e-11ea-9dc4-539994724adb.png">

2. Similarly, I've been trying to use "react svgs" for the frontity log for other button types, but it's difficult to add the hover effect then. I am happy to just use `::before` CSS pseudoclasses BUT we will then not be able to change the `opacity` or `fill` of the logos. Is that also okay with you?

3. The border on this button:
<img width="290" alt="Screenshot 2020-03-11 at 11 58 57" src="https://user-images.githubusercontent.com/5417266/76442959-b23c7080-638f-11ea-9304-aa81c72b8123.png">
should be added with a separate processor? Or should I just include it in the processor for that button?

**Comment by michalczaplinski** [comment]
@SantosGuillamot 

Two more things:
1. Should the **text button** also move 2px down when it's _active_? From the design point of view I think it's gonna look weird 😅 

2. Also in the **text-button**, should the logo also move 2px to the right on _hover_? It looks like this on the design but I think it would look weird.

**Comment by SantosGuillamot** [comment]
Yes, it's okay that the logo is fixed. We investigated how `svg` works but WordPress adds the `svg` like images, so you can't use the `fill` property. But in this case is okay because the `svg` already has the color and it doesn't change.

I'll review the PR now :slightly_smiling_face:
