### ISSUE TITLE
Frontity website has layout issues and missing content on MS Edge on Windows

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity.org#104]
Microsoft EdgeHTML 18.18362
Microdsoft Edge 44.18362.449.0 

This is a pretty recent version of Edge so I assume that the page does not work on Edge at all :( 

The main problem is that the hero text does not show up:

![frontity homepage](https://user-images.githubusercontent.com/5417266/81232994-88807e00-8fbb-11ea-8d1e-9d9fe5e8161b.jpeg)

But also some of the icons are misaligned:

![frontity page](https://user-images.githubusercontent.com/5417266/81232996-8ae2d800-8fbb-11ea-8524-7bf620bad110.jpeg)

The console (the first line is an error and the following ones are a warning) :

```
SCRIPT5007: SCRIPT5007: Unable to get property 'addEventListener' of undefined or null reference
frontity.org (3,113)

[Amplitude] WARNING: Property key "utm_campaign" with invalid value type undefined, ignoring

[Amplitude] WARNING: Property key "utm_medium" with invalid value type undefined, ignoring

[Amplitude] WARNING: Property key "utm_source" with invalid value type undefined, ignoring
```

**Comment by SantosGuillamot** [comment]
I've been doing some tests on Microsoft Edge and it's happening to me as well. However, it doesn't seem to be related to the warning you posted, it seems to be related to [these lines of code](https://github.com/frontity/frontity.org/blob/dev/packages/frontity-org-theme/src/components/styles/homepage.tsx#L45-L58). If I remove that part the hero shows correctly. Do you know what it could be? Is there another easy way of developing that part?

**Comment by michalczaplinski** [comment]
Looks like `clip-path` is only supported in the latest version of Edge (79+, released in Jan 2020): 

https://caniuse.com/#feat=mdn-css_properties_clip-path_basic_shape

We I think that we can use the following technique to fix it:
```
<div class="edges">
  <h1>Angled Edges</h1>
</div>
```


```
.edges {
  color: #fff;
  padding: 20% 20px;
  background: #41ade5;
  position: relative;
  z-index: 1;
}

.edges::after {
  bottom: 0;
  transform: skewY(-4deg); /* change to 4px if you want to skew the other way */
  transform-origin: 100%;    /* change to 0% if you want to skew the other way

  background: inherit;
  content: '';
  display: block;
  height: 100%;
  left: 0;
  position: absolute;
  right: 0;
  z-index: -1;
}
```

[Here's an example](https://jsbin.com/lohicacara/edit?html,css,output)

**Comment by SantosGuillamot** [comment]
Okay, that seems to be the problem yes :slightly_smiling_face: I think what is happening is that, as clip-path is not being applied, the second background is on top of the main content, so just by adding a `z-index` prop it's placed correctly. The `clip-path` still won't work in Microsoft Edge old versions, but I think that's not a problem. I've made a quick PR to solve it #105 .

**Comment by michalczaplinski** [comment]
sweet! good catch @SantosGuillamot 🙂
