### ISSUE TITLE
Images of our blog are redirecting to the wrong URL

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity.org#109]
Some old images of our blog are redirecting to the wrong URLs.

For example, this image https://blog.frontity.org/wp-content/uploads/2019/07/twenty-nineteen-frontity-theme.png is redirecting to https://frontity.org/blog/wp-content/uploads/2019/07/twenty-nineteen-frontity-theme.png and its returns a 404 page.

It should instead redirect to https://wp.frontity.org/wp-content/uploads/2019/07/twenty-nineteen-frontity-theme.png.

**Comment by luisherranz** [comment]
Solved 👍
