### ISSUE TITLE
Fix layout in 404 page

### ISSUE THREAD

**Issue by ardillan** [frontity/frontity.org#125]
Just discovered that the 404 page is not rendering correctly. 

![Screenshot 2020-06-22 at 23 10 30](https://user-images.githubusercontent.com/8223095/85336117-6779db00-b4de-11ea-88ca-bbfd7c49df35.png)

I've made a quick search and seems to be the that the `header-styles.ts` can be the main cause. Happens on both desktop and mobile.

**Tested on**:

- macOS 10.15.5

- Safari 13.1.1
- Firefox 77.0.1 
- Google Chrome 83.0.4103

**Comment by luisherranz** [comment]
Thanks for the report @ardillan.

@santosguillamot this seems like a CSS problem. A bit of a mess between styles of the "homepage" and sections that are not consistent in the 404 pages.

**Comment by SantosGuillamot** [comment]
I'll take a look at it, thanks for noticing it :slightly_smiling_face:

**Comment by SantosGuillamot** [comment]
I created this PR #127 to fix this.
