### ISSUE TITLE
Frontity default state.source don’t fetch all items once in loop

### ISSUE THREAD

**Issue by harpreet9629** [frontity/frontity.org#165]
Frontity default state.source don’t fetch all items inside loop. I am trying to fetch posts from custom api route which return id, link, type, slug in json. When i console.log custom route it returns all 5 items. but when i fetch data with state.source[item.type][item.id] it fetch only first 1 from json output. If i tried to return all posts data in custom route and show post title, post link direct in component and click on link it move to 404 page.

please help, if i can’t solve this issue i can’t run site with frontity 

```
const FrontPage = ({state, actions}) => {

    useEffect(() => {
        actions.source.fetch("getFeaturedPosts");
        FeaturedPostSection.preload();
    }, []);

//   const data = state.source.get(state.router.link);

//   const [firstThreePosts, othersPosts] = splitPosts(state, data.items);

    const data = state.source.get("getFeaturedPosts");

    const [firstThreePosts, othersPosts] = splitPosts(state, data.items);

    return data.isReady ?  (
        <>
            <FrontPageContainer>
                <FeaturedPostSection data={firstThreePosts.map(post => formatPostData(state, post))} />
           </FrontPageContainer>
        </>

    ) : null;
};
```

export default connect(FrontPage);

```
export function splitPosts(state, routeData) {
  const firstThreePosts = [];
  const otherPosts = [];
  routeData.forEach((item, idx) => {
    console.log(item.id);
    const itemData = state.source[item.type][item.id];
    if (idx < 3) firstThreePosts.push(itemData);
    else otherPosts.push(itemData);
  });

  return [firstThreePosts, otherPosts];
}
```

![Screenshot_2](https://user-images.githubusercontent.com/26606638/108874928-ae4a4280-7622-11eb-992c-ec69fb39f970.png)

**Comment by SantosGuillamot** [comment]
This doesn't seem related to this repo, which is for the [Frontity site](https://github.com/frontity/frontity/issues/726). I've seen that you opened the [same issue](https://github.com/frontity/frontity/issues/726) in the `frontity` repo, so I'm closing this one.
