### ISSUE TITLE
Mobile menu does not close on click

### ISSUE THREAD

**Issue by kasperaamodt** [frontity/frontity.org#186]
Hi,

Was browsing the site on mobile, and noticed that when i use the menu, it does not close itself after I click a link and the page is opened, so I have to manually close it.

**Comment by luisherranz** [comment]
Yeah, thanks for reporting this @kasperaamodt.

It seems like we are using internal state for that toggle: https://github.com/frontity/frontity.org/blob/dev/packages/frontity-org-theme/src/components/headers/index.tsx#L19-L20

```js
// Store if the menu is open (for the mobile view).
const [isMenuOpen, setIsMenuOpen] = React.useState(false);
```

So I guess we could use a `useEffect` to close it whenever `state.router.link` changes. Something like:

```js
// Store if the menu is open (for the mobile view).
const [isMenuOpen, setIsMenuOpen] = React.useState(false);

useEffect(() => {
  setIsMenuOpen(false);
}, [state.router.link])
```

I'll label it with `good-first-issue`. PRs are welcomed! 🙂

**Comment by kasperaamodt** [comment]
Hi @luisherranz,

I wanted to start on a pr to see if I'm able to fix this, but when I clone the repo and try to run it in localhost, I get this error message:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Any idea on how to fix this? I cloned the master branch.

**Comment by luisherranz** [comment]
The same thing happened to me last week because of npm 7. Make sure you don't have any nested `node_modules` folders.

If that doesn't help:
- Delete root `node_modules`.
- Delete `node_modules` of `packages/xxx`.
- Delete `package-lock.json`.
- Run `npm install` again.

**Comment by kasperaamodt** [comment]
Thanks, @luisherranz, that did the trick!

I have opened a PR, #192.

**Comment by luisherranz** [comment]
Awesome 🙂

**Comment by kasperaamodt** [comment]
Merged. 😄
