### ISSUE TITLE
Processor for mobile/desktop only

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity.org#19]
## Description
There are some elements that will be shown only in the desktop view, and other ones that will be shown only in mobile. We have to be able to define this from Gutenberg.

We could pass a class `desktop-only` and `mobile-only` in order to process this from Frontity.

## Where to check
* `/common-styles/` page -> Mobile only & Desktop only headings

**Comment by iamuchejude** [comment]
What are the breakpoints (screen width) for desktop and mobile screen? I plan to use: `@media only screen and (max-width: 768px) {...}` for mobile devices including tablets

**Comment by SantosGuillamot** [comment]
I'll ask the designer, but I guess what you are planning to use is okay for the moment.

**Comment by luisherranz** [comment]
Blocked until we figure out how to solve this: https://github.com/frontity/frontity.org/pull/29#pullrequestreview-370454406
