### ISSUE TITLE
Merge dev to master

### ISSUE THREAD

**Issue by kasperaamodt** [frontity/frontity.org#196]
Hi,

How often do you merge dev to master to get changes live? One of the PR's that I submitted should be published asap, considering none of the CF7 forms you have on the site are working.

**Comment by luisherranz** [comment]
Mario (@santosguillamot) usually takes care of the releases but he is on holiday. I'll do the release today. Thanks Kasper! 🙂

**Comment by luisherranz** [comment]
Released! Thanks again Kasper :)
