### ISSUE TITLE
Fetch all the common elements for the pages

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity.org#37]
## Description
There are some elements like the header, footer or the newsletter, that will be included in all the pages. In order to get their data, we have used a Custom Post Type named `Template Parts`, where all of them are included.

We should fetch this data at `https://wp.frontity.org/wp-json/wp/v2/template-parts` and populate the state so the content can be used to show them in each page.

**Comment by luisherranz** [comment]
I think we are going to need the ids of the template-parts that are required.

Apart from that, I guess we can do the fetch in the `beforeSSR` action.

**Comment by michalczaplinski** [comment]
> I think we are going to need the ids of the template-parts that are required.
Could you explain in more details what this means?

I thought that adding this should "just work" but I think I misunderstand what is required here:
```
state: {
        source: {
          api: "https://wp.frontity.org/wp-json",
          postTypes: [
            {
              type: "template-parts",
              endpoint: "template-parts"
            }
          ]
        }
      }
```

Where is that data for the `template-parts` stored in our wordpress?

**Comment by luisherranz** [comment]
https://wp.frontity.org/wp-json/wp/v2/template-parts will fetch the last 10 template parts, no matter what. 

We need the ids of the template parts we are using, to do https://wp.frontity.org/wp-json/wp/v2/template-parts?include=4308,4310.

**Comment by SantosGuillamot** [comment]
>https://wp.frontity.org/wp-json/wp/v2/template-parts will fetch the last 10 template parts created, no matter what.

So far all the current template-parts must be included, there are only 4. I think, at least with the current design, we should only include template-parts that are really needed. Anyway, I'm not sure what's better, I trust your opinion, we could include all the ids that are currently in that endpoint.

>Where is that data for the template-parts stored in our wordpress?

You can find the `template-parts` at the left menu on the WP Admin panel -> Appereance -> Template parts.

>I thought that adding this should "just work" but I think I misunderstand what is required here:

I guess this could be one solution, using Custom Post Types. The problem is that the `type` you are using is not correct. Gutenberg named the type `wp_template_part`. You can check [the docs](https://docs.frontity.org/api-reference-1/wordpress-source#state-source-posttypes) on how to find it.
![Screenshot from 2020-03-13 09-28-37](https://user-images.githubusercontent.com/34552881/76603336-1173bf80-650d-11ea-8c16-90c96ff8462e.png)

Apart from that, if we go with this solution, I think we'd need to add the `archive` field as well, in order to fetch all the elements at the same type. Something like `actions.source.fetch("/template-parts-archive"). After that, if we want to get the info about an specific element we just have to do `state.source.get("/wp_template_part/fixed-header/")`

However, if we need to use custom params as `?include=4222,4223...`, I think we'd need to create a custom handler to fetch the data from the `template-parts` endpoint and populate the state. Could you confirm if this is correct @luisherranz ?

**Comment by luisherranz** [comment]
We can also:
- Fetch them by slug.
- Save the slugs in the settings.

```js
const fetchTemplates = async ({ state }) => {
  await Promise.all(state.theme.templates.map(slug =>
    actions.source.fetch(`/wp_template_part/${slug}`)
  ));
};
```

_I'm not sure what's the `wp_template_part` prefix._

**Comment by SantosGuillamot** [comment]
That way, we would be doing one fetch per `slug` right? (Right now it'd be 4 different fetches).
>I'm not sure what's the wp_template_part prefix.

It's the prefix Gutenberg is adding:
![Screenshot from 2020-03-13 10-03-40](https://user-images.githubusercontent.com/34552881/76606106-f9526f00-6511-11ea-9424-a71d033338e1.png)

**Comment by luisherranz** [comment]
> That way, we would be doing one fetch per slug right? (Right now it'd be 4 different fetches).

Yes.

If we specify the ids or slugs in our code, then those fetches won't depend on the WordPress dashboard and things will never break. If we don't do that, then, for example, someone adding new template parts to test something else could break our site without even noticing because our site will only fetch the last 10 template parts.

> It's the prefix Gutenberg is adding:

Oh, I see. Thanks :)

**Comment by SantosGuillamot** [comment]
Okay, I like the approach of specifying the template parts we need in Frontity. Once the web is finished, we shouldn't add more `template-parts`, and if we have to, we still would need to place them in the `index.js` file I guess.

**Comment by michalczaplinski** [comment]
So, we should fetch by slug like @luisherranz has described? I've started on this approach already :)  https://github.com/frontity/frontity.org/issues/37#issuecomment-598616219

1. Do we then need a custom handler? I thought that it was not necessary?
2. Simply fetching the data as mentioned, results in an error:
```js
state: {
    theme: {
      colors: {},
      templates: [4417, 4308, 4310, 4305]
    }
  },
  actions: {
    theme: {
      beforeSSR: ({ state, actions }) => async ({ ctx }) => {
        const data = await Promise.all(
          state.theme.templates.map(slug =>
            actions.source.fetch(`/template-parts/${slug}`)
          )
        );
        console.log("ready", data);
      }
    }
  },
```

```
ServerError: post type from endpoints "posts,pages,media" with slug "4310" not found
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:9:21)
```

I'm also not sure why the `endpoint` in that error message is "posts,pages,media" instead of `template-parts`. Investigating now.

**Comment by SantosGuillamot** [comment]
Not sure if we need a custom handler or not, if we can avoid it I guess it'd be better. Regarding the code you shared maybe it isn't working for two reasons:
* You are using `/template-parts/` instead of `wp_template_part` (it's the url Gutenberg creates) inside the `actions.source.fetch`.
* Inside `state.theme.templates` you are adding `ids` instead of `slugs`. It should look similar to `templates: ["fixed-header", "header", "footer", "newsletter"]`.

**Comment by luisherranz** [comment]
I don't know if you did it yet, but you also need to add `wp_template_part` as a custom post type. 

By the way, always start the PRs as soon as possible because if not the rest of the team cannot look/contribute/test the code :)
