### ISSUE TITLE
Reduce scripts budget back to 200kbs

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity.org#68]
Now that @SantosGuillamot has fixed the performance problems in https://github.com/frontity/frontity.org/pull/66 we must reduce the scripts budget size to avoid this problem in the future.

This is the commit that we have to revert: https://github.com/frontity/frontity.org/commit/cbe8bf0f5ae09aeffe31fb0b3341882e157242ba

**Comment by SantosGuillamot** [comment]
I am planning to do it after investigating how to lazy load tweets as in my last commit the bundle size was 196kb, too close to the limit.

**Comment by luisherranz** [comment]
Moved to blocked until you investigate that then 👍

**Comment by luisherranz** [comment]
Fixed in https://github.com/frontity/frontity.org/pull/90.
