### ISSUE TITLE
Wrong styles on "visited" links?

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/frontity.org#84]
Browser: Chrome. Versión 81.0.4044.113 (Build oficial) (64 bits)
OS: Mac 10.14.6

Shouldn't the text in this button be white all the time (normal and hover)?

![Captura de pantalla 2020-04-23 a las 9 41 46](https://user-images.githubusercontent.com/422576/80073580-46315880-8548-11ea-9c95-5ec58b36ee39.png)

I think this has something to do with the styles in visited links

**Comment by luisherranz** [comment]
Fixed in https://github.com/frontity/frontity.org/pull/91.
