### ISSUE TITLE
Blog Search is not working

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/frontity.org#88]
The search in the blog is not working.
It redirects you to → https://frontity.org/?s=react when it should redirect you to https://frontity.org/blog/?s=react

**Comment by luisherranz** [comment]
Thank @juanmaguitar.

We have decided yesterday to move `twentytwenty-theme` to a local package to solve this problem until we have [router converters](https://community.frontity.org/t/router-converters/1514).
