### ISSUE TITLE
Hero section does not render as expected

### ISSUE THREAD

**Issue by iamuchejude** [frontity/frontity.org#96]
The hero section of the deployed website happens to be slightly different from what's on the design.

**Current**
![Current](https://wp.frontity.org/wp-content/uploads/2020/04/current-hero.png)

**Expected**
![Expected](https://wp.frontity.org/wp-content/uploads/2020/04/new-design.png)

**Comment by SantosGuillamot** [comment]
Closing this as it doesn't seem to apply anymore.
