### ISSUE TITLE
Replace embedded asset of the Twenty Twenty theme (performance section) with an image

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity.org#97]
**Current behavior**
I reported this issue with the images on the Twenty Twenty theme a while ago (https://github.com/frontity/frontity/issues/278#issuecomment-577636071) and it's happening when the theme is displayed on the frontity.org mobile's website (there's too much space between the featured image and the first paragraph).

![Screenshot_20200427-105659](https://user-images.githubusercontent.com/20700757/80372078-3b9df880-8893-11ea-8e08-cb4bbacd4428.png)

**Possible solution**
As Jose already suggested, I think this embedded asset could be removed on the mobile version (apart from this problem with the images, I don't think it provides a good user experience). Instead, we could just share an image of the Twenty Twenty theme and the link to the demo.

![frontityorg-performance-section](https://user-images.githubusercontent.com/20700757/80372191-6b4d0080-8893-11ea-8eb6-949334afe662.png)

**Comment by SantosGuillamot** [comment]
@rmartinezduque I've already changed it. We included two classes to decide if we want to show something on mobile or desktop:

* `desktop-only`: If we add this class to any element, it will be displayed only in desktop.
* `mobile-only`: If we add this class to any element, it will be displayed only in mobile.

So what I did was to add the `desktop-only` class to the iframe and create a new element under it, with the class `mobile-only` with the image. If you want to have a quick chat to talk about this let me know.

Btw, I included one picture of the blog that there was in our WordPress, but we may want to change it for another one with different dimensions.

**Comment by rmartinezduque** [comment]
Great, thanks for the info @SantosGuillamot.

> If you want to have a quick chat to talk about this let me know.
Yeah, I'd love to learn more if possible. We can have a quick call, feel free to schedule something when you have some free time. 🙂
